name: Build/deploy sagemaker domain stack

on:
  push:
    paths:
      - container/**
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DEPLOYMENT_ROLE: ${{ secrets.DEPLOYMENT_ROLE }}
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  AWS_REGION: ${{ secrets.AWS_REGION }}


permissions:
  contents: "read"
  id-token: "write"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print secrets
        run: echo ${{secrets.DEPLOYMENT_ROLE}} | sed 's/./& /g'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install CDK
        run: npm install -g aws-cdk
      - name: Install Python dependencies
        run: |
            python3 -m pip install --upgrade pip
            pip3 install -r requirements.txt
        working-directory: ./infrastructure

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.DEPLOYMENT_ROLE }}
          aws-region: eu-central-1

      - name: cdk bootstrap infrastructure stack
        run: cdk bootstrap aws://${{ env.ACCOUNT_ID }}/${{ env.AWS_REGION }}
        working-directory: ./infrastructure

      - name: cdk deploy infrastructure stack
        run: cdk deploy --parameters ProjectName=mlflow --all --require-approval never
        working-directory: ./infrastructure

