name: Deploy Inference Endpoint

on:
  push:
    branches:
      - main
    paths:
      - src/model_deploy/**
      - cfg/model_deploy.yaml
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  DEPLOYMENT_ROLE: ${{ secrets.DEPLOYMENT_ROLE }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install CDK
        run: npm install -g aws-cdk
      - name: Install Python dependencies
        run: |
            python3 -m pip install --upgrade pip
            pip3 install -r requirements.txt
        working-directory: ./infrastructure

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.DEPLOYMENT_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: cdk bootstrap inference stack
        run: cdk bootstrap aws://${{ env.ACCOUNT_ID }}/${{ env.AWS_REGION }}
        working-directory: ./src/model_deploy

      - name: cdk deploy inference stack
        run: cdk deploy --all --require-approval never
        working-directory: ./src/model_deploy

